controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_home:
    path: /home
    controller: App\Controller\HomeController::index


app_hi:
    path: /hi/{hanane?Anonymous}
    controller: App\Controller\HomeController::hi
    requirements:
        hanane: '[a-z]+'